# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replicator_pb2 as replicator__pb2


class DBReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute_query = channel.unary_unary(
                '/DBReplicator/execute_query',
                request_serializer=replicator__pb2.Request.SerializeToString,
                response_deserializer=replicator__pb2.Response.FromString,
                )


class DBReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def execute_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute_query': grpc.unary_unary_rpc_method_handler(
                    servicer.execute_query,
                    request_deserializer=replicator__pb2.Request.FromString,
                    response_serializer=replicator__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DBReplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DBReplicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def execute_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBReplicator/execute_query',
            replicator__pb2.Request.SerializeToString,
            replicator__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
